version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app:rw
      - ./database/:/database:rw
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_MIGRATIONS_PATH: ${DB_MIGRATIONS_PATH}
    depends_on:
      - "db"
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  test:
    build:
      context: ./
      dockerfile: Dockerfile-tests
    volumes:
      - ./:/backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_MIGRATIONS_PATH: /backend/database/migrations
    depends_on:
      - "db"
    entrypoint:
      [
        "/wait-for-it.sh",
        "db:5432",
        "--",
        "go",
        "test",
        "-p",
        "1",
        "./...",
        "-coverprofile=c.out",
      ]
