FROM golang:1.16-alpine AS build-env
RUN apk --no-cache add build-base git gcc
WORKDIR /app
COPY ./ /app
RUN go get github.com/githubnemo/CompileDaemon
ENTRYPOINT CompileDaemon --build="go build -o backend" --command=./backend
