DROP TABLE IF EXISTS quote_book;
DROP TABLE IF EXISTS witnesses;
DROP TABLE IF EXISTS quotes;

DROP SEQUENCE IF EXISTS quote_book_id_seq;
DROP SEQUENCE IF EXISTS witness_id_seq;
DROP SEQUENCE IF EXISTS quote_id_seq;
